version: "3.9"

services:
  etheur:
    build:
      context: .
    container_name: etheur
    volumes:
      - ./market/etheur/config.json:/app/config.json
      - ./market/etheur/pycryptobot.log:/app/pycryptobot.log
      - ./market/etheur/graphs:/app/graphs
      - ./market/etheur/coinbase.key:/app/coinbase.key
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      restart_policy:
        condition: on-failure
